//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     ANTLR Version: 4.8
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from MFSHParser.g4 by ANTLR 4.8

// Unreachable code detected
#pragma warning disable 0162
// The variable '...' is assigned but its value is never used
#pragma warning disable 0219
// Missing XML comment for publicly visible type or member '...'
#pragma warning disable 1591
// Ambiguous reference in cref attribute
#pragma warning disable 419

namespace Eir.MFSH.Parser {
using System;
using System.IO;
using System.Text;
using System.Diagnostics;
using System.Collections.Generic;
using Antlr4.Runtime;
using Antlr4.Runtime.Atn;
using Antlr4.Runtime.Misc;
using Antlr4.Runtime.Tree;
using DFA = Antlr4.Runtime.Dfa.DFA;

[System.CodeDom.Compiler.GeneratedCode("ANTLR", "4.8")]
[System.CLSCompliant(false)]
public partial class MFSHParser : Parser {
	protected static DFA[] decisionToDFA;
	protected static PredictionContextCache sharedContextCache = new PredictionContextCache();
	public const int
		MFSH=1, TEXTA=2, TEXTB=3, TEXTC=4, TEXTD=5, TICKTEXT=6, CR=7, APPLY=8, 
		END=9, INCOMPATIBLE=10, MACRO=11, ONCE=12, STRING=13, MULTILINE_STRING=14, 
		OPAR=15, COMMA=16, CPAR=17, GT=18, NAME=19, MFSHCont=20, MFSHExit=21, 
		MFSHCR=22, MFSH_SPACE=23;
	public const int
		RULE_document = 0, RULE_command = 1, RULE_textA = 2, RULE_textB = 3, RULE_textC = 4, 
		RULE_textD = 5, RULE_tickText = 6, RULE_mfshExit = 7, RULE_mfshCmds = 8, 
		RULE_mfshCmd = 9, RULE_apply = 10, RULE_end = 11, RULE_incompatible = 12, 
		RULE_macro = 13, RULE_redirect = 14, RULE_anyString = 15, RULE_multiLineString = 16, 
		RULE_singleString = 17;
	public static readonly string[] ruleNames = {
		"document", "command", "textA", "textB", "textC", "textD", "tickText", 
		"mfshExit", "mfshCmds", "mfshCmd", "apply", "end", "incompatible", "macro", 
		"redirect", "anyString", "multiLineString", "singleString"
	};

	private static readonly string[] _LiteralNames = {
		null, null, null, null, null, null, null, null, "'apply'", "'end'", "'incompatible'", 
		"'macro'", "'once'", null, null, "'('", "','", "')'", "'>'", null, null, 
		"'\n'"
	};
	private static readonly string[] _SymbolicNames = {
		null, "MFSH", "TEXTA", "TEXTB", "TEXTC", "TEXTD", "TICKTEXT", "CR", "APPLY", 
		"END", "INCOMPATIBLE", "MACRO", "ONCE", "STRING", "MULTILINE_STRING", 
		"OPAR", "COMMA", "CPAR", "GT", "NAME", "MFSHCont", "MFSHExit", "MFSHCR", 
		"MFSH_SPACE"
	};
	public static readonly IVocabulary DefaultVocabulary = new Vocabulary(_LiteralNames, _SymbolicNames);

	[NotNull]
	public override IVocabulary Vocabulary
	{
		get
		{
			return DefaultVocabulary;
		}
	}

	public override string GrammarFileName { get { return "MFSHParser.g4"; } }

	public override string[] RuleNames { get { return ruleNames; } }

	public override string SerializedAtn { get { return new string(_serializedATN); } }

	static MFSHParser() {
		decisionToDFA = new DFA[_ATN.NumberOfDecisions];
		for (int i = 0; i < _ATN.NumberOfDecisions; i++) {
			decisionToDFA[i] = new DFA(_ATN.GetDecisionState(i), i);
		}
	}

		public MFSHParser(ITokenStream input) : this(input, Console.Out, Console.Error) { }

		public MFSHParser(ITokenStream input, TextWriter output, TextWriter errorOutput)
		: base(input, output, errorOutput)
	{
		Interpreter = new ParserATNSimulator(this, _ATN, decisionToDFA, sharedContextCache);
	}

	public partial class DocumentContext : ParserRuleContext {
		public ITerminalNode Eof() { return GetToken(MFSHParser.Eof, 0); }
		public CommandContext[] command() {
			return GetRuleContexts<CommandContext>();
		}
		public CommandContext command(int i) {
			return GetRuleContext<CommandContext>(i);
		}
		public DocumentContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_document; } }
		public override TResult Accept<TResult>(IParseTreeVisitor<TResult> visitor) {
			IMFSHParserVisitor<TResult> typedVisitor = visitor as IMFSHParserVisitor<TResult>;
			if (typedVisitor != null) return typedVisitor.VisitDocument(this);
			else return visitor.VisitChildren(this);
		}
	}

	[RuleVersion(0)]
	public DocumentContext document() {
		DocumentContext _localctx = new DocumentContext(Context, State);
		EnterRule(_localctx, 0, RULE_document);
		int _la;
		try {
			EnterOuterAlt(_localctx, 1);
			{
			State = 39;
			ErrorHandler.Sync(this);
			_la = TokenStream.LA(1);
			while ((((_la) & ~0x3f) == 0 && ((1L << _la) & ((1L << MFSH) | (1L << TEXTA) | (1L << TEXTB) | (1L << TEXTC) | (1L << TEXTD) | (1L << TICKTEXT) | (1L << MFSHExit))) != 0)) {
				{
				{
				State = 36; command();
				}
				}
				State = 41;
				ErrorHandler.Sync(this);
				_la = TokenStream.LA(1);
			}
			State = 42; Match(Eof);
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class CommandContext : ParserRuleContext {
		public TextAContext textA() {
			return GetRuleContext<TextAContext>(0);
		}
		public TextBContext textB() {
			return GetRuleContext<TextBContext>(0);
		}
		public TextCContext textC() {
			return GetRuleContext<TextCContext>(0);
		}
		public TextDContext textD() {
			return GetRuleContext<TextDContext>(0);
		}
		public TickTextContext tickText() {
			return GetRuleContext<TickTextContext>(0);
		}
		public MfshExitContext mfshExit() {
			return GetRuleContext<MfshExitContext>(0);
		}
		public MfshCmdsContext mfshCmds() {
			return GetRuleContext<MfshCmdsContext>(0);
		}
		public CommandContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_command; } }
		public override TResult Accept<TResult>(IParseTreeVisitor<TResult> visitor) {
			IMFSHParserVisitor<TResult> typedVisitor = visitor as IMFSHParserVisitor<TResult>;
			if (typedVisitor != null) return typedVisitor.VisitCommand(this);
			else return visitor.VisitChildren(this);
		}
	}

	[RuleVersion(0)]
	public CommandContext command() {
		CommandContext _localctx = new CommandContext(Context, State);
		EnterRule(_localctx, 2, RULE_command);
		try {
			State = 51;
			ErrorHandler.Sync(this);
			switch (TokenStream.LA(1)) {
			case TEXTA:
				EnterOuterAlt(_localctx, 1);
				{
				State = 44; textA();
				}
				break;
			case TEXTB:
				EnterOuterAlt(_localctx, 2);
				{
				State = 45; textB();
				}
				break;
			case TEXTC:
				EnterOuterAlt(_localctx, 3);
				{
				State = 46; textC();
				}
				break;
			case TEXTD:
				EnterOuterAlt(_localctx, 4);
				{
				State = 47; textD();
				}
				break;
			case TICKTEXT:
				EnterOuterAlt(_localctx, 5);
				{
				State = 48; tickText();
				}
				break;
			case MFSHExit:
				EnterOuterAlt(_localctx, 6);
				{
				State = 49; mfshExit();
				}
				break;
			case MFSH:
				EnterOuterAlt(_localctx, 7);
				{
				State = 50; mfshCmds();
				}
				break;
			default:
				throw new NoViableAltException(this);
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class TextAContext : ParserRuleContext {
		public ITerminalNode TEXTA() { return GetToken(MFSHParser.TEXTA, 0); }
		public TextAContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_textA; } }
		public override TResult Accept<TResult>(IParseTreeVisitor<TResult> visitor) {
			IMFSHParserVisitor<TResult> typedVisitor = visitor as IMFSHParserVisitor<TResult>;
			if (typedVisitor != null) return typedVisitor.VisitTextA(this);
			else return visitor.VisitChildren(this);
		}
	}

	[RuleVersion(0)]
	public TextAContext textA() {
		TextAContext _localctx = new TextAContext(Context, State);
		EnterRule(_localctx, 4, RULE_textA);
		try {
			EnterOuterAlt(_localctx, 1);
			{
			State = 53; Match(TEXTA);
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class TextBContext : ParserRuleContext {
		public ITerminalNode TEXTB() { return GetToken(MFSHParser.TEXTB, 0); }
		public TextBContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_textB; } }
		public override TResult Accept<TResult>(IParseTreeVisitor<TResult> visitor) {
			IMFSHParserVisitor<TResult> typedVisitor = visitor as IMFSHParserVisitor<TResult>;
			if (typedVisitor != null) return typedVisitor.VisitTextB(this);
			else return visitor.VisitChildren(this);
		}
	}

	[RuleVersion(0)]
	public TextBContext textB() {
		TextBContext _localctx = new TextBContext(Context, State);
		EnterRule(_localctx, 6, RULE_textB);
		try {
			EnterOuterAlt(_localctx, 1);
			{
			State = 55; Match(TEXTB);
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class TextCContext : ParserRuleContext {
		public ITerminalNode TEXTC() { return GetToken(MFSHParser.TEXTC, 0); }
		public TextCContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_textC; } }
		public override TResult Accept<TResult>(IParseTreeVisitor<TResult> visitor) {
			IMFSHParserVisitor<TResult> typedVisitor = visitor as IMFSHParserVisitor<TResult>;
			if (typedVisitor != null) return typedVisitor.VisitTextC(this);
			else return visitor.VisitChildren(this);
		}
	}

	[RuleVersion(0)]
	public TextCContext textC() {
		TextCContext _localctx = new TextCContext(Context, State);
		EnterRule(_localctx, 8, RULE_textC);
		try {
			EnterOuterAlt(_localctx, 1);
			{
			State = 57; Match(TEXTC);
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class TextDContext : ParserRuleContext {
		public ITerminalNode TEXTD() { return GetToken(MFSHParser.TEXTD, 0); }
		public TextDContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_textD; } }
		public override TResult Accept<TResult>(IParseTreeVisitor<TResult> visitor) {
			IMFSHParserVisitor<TResult> typedVisitor = visitor as IMFSHParserVisitor<TResult>;
			if (typedVisitor != null) return typedVisitor.VisitTextD(this);
			else return visitor.VisitChildren(this);
		}
	}

	[RuleVersion(0)]
	public TextDContext textD() {
		TextDContext _localctx = new TextDContext(Context, State);
		EnterRule(_localctx, 10, RULE_textD);
		try {
			EnterOuterAlt(_localctx, 1);
			{
			State = 59; Match(TEXTD);
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class TickTextContext : ParserRuleContext {
		public ITerminalNode TICKTEXT() { return GetToken(MFSHParser.TICKTEXT, 0); }
		public TickTextContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_tickText; } }
		public override TResult Accept<TResult>(IParseTreeVisitor<TResult> visitor) {
			IMFSHParserVisitor<TResult> typedVisitor = visitor as IMFSHParserVisitor<TResult>;
			if (typedVisitor != null) return typedVisitor.VisitTickText(this);
			else return visitor.VisitChildren(this);
		}
	}

	[RuleVersion(0)]
	public TickTextContext tickText() {
		TickTextContext _localctx = new TickTextContext(Context, State);
		EnterRule(_localctx, 12, RULE_tickText);
		try {
			EnterOuterAlt(_localctx, 1);
			{
			State = 61; Match(TICKTEXT);
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class MfshExitContext : ParserRuleContext {
		public ITerminalNode MFSHExit() { return GetToken(MFSHParser.MFSHExit, 0); }
		public MfshExitContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_mfshExit; } }
		public override TResult Accept<TResult>(IParseTreeVisitor<TResult> visitor) {
			IMFSHParserVisitor<TResult> typedVisitor = visitor as IMFSHParserVisitor<TResult>;
			if (typedVisitor != null) return typedVisitor.VisitMfshExit(this);
			else return visitor.VisitChildren(this);
		}
	}

	[RuleVersion(0)]
	public MfshExitContext mfshExit() {
		MfshExitContext _localctx = new MfshExitContext(Context, State);
		EnterRule(_localctx, 14, RULE_mfshExit);
		try {
			EnterOuterAlt(_localctx, 1);
			{
			State = 63; Match(MFSHExit);
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class MfshCmdsContext : ParserRuleContext {
		public ITerminalNode MFSH() { return GetToken(MFSHParser.MFSH, 0); }
		public MfshCmdContext[] mfshCmd() {
			return GetRuleContexts<MfshCmdContext>();
		}
		public MfshCmdContext mfshCmd(int i) {
			return GetRuleContext<MfshCmdContext>(i);
		}
		public MfshCmdsContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_mfshCmds; } }
		public override TResult Accept<TResult>(IParseTreeVisitor<TResult> visitor) {
			IMFSHParserVisitor<TResult> typedVisitor = visitor as IMFSHParserVisitor<TResult>;
			if (typedVisitor != null) return typedVisitor.VisitMfshCmds(this);
			else return visitor.VisitChildren(this);
		}
	}

	[RuleVersion(0)]
	public MfshCmdsContext mfshCmds() {
		MfshCmdsContext _localctx = new MfshCmdsContext(Context, State);
		EnterRule(_localctx, 16, RULE_mfshCmds);
		int _la;
		try {
			EnterOuterAlt(_localctx, 1);
			{
			State = 65; Match(MFSH);
			State = 69;
			ErrorHandler.Sync(this);
			_la = TokenStream.LA(1);
			while ((((_la) & ~0x3f) == 0 && ((1L << _la) & ((1L << APPLY) | (1L << END) | (1L << INCOMPATIBLE) | (1L << MACRO))) != 0)) {
				{
				{
				State = 66; mfshCmd();
				}
				}
				State = 71;
				ErrorHandler.Sync(this);
				_la = TokenStream.LA(1);
			}
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class MfshCmdContext : ParserRuleContext {
		public ApplyContext apply() {
			return GetRuleContext<ApplyContext>(0);
		}
		public EndContext end() {
			return GetRuleContext<EndContext>(0);
		}
		public IncompatibleContext incompatible() {
			return GetRuleContext<IncompatibleContext>(0);
		}
		public MacroContext macro() {
			return GetRuleContext<MacroContext>(0);
		}
		public MfshCmdContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_mfshCmd; } }
		public override TResult Accept<TResult>(IParseTreeVisitor<TResult> visitor) {
			IMFSHParserVisitor<TResult> typedVisitor = visitor as IMFSHParserVisitor<TResult>;
			if (typedVisitor != null) return typedVisitor.VisitMfshCmd(this);
			else return visitor.VisitChildren(this);
		}
	}

	[RuleVersion(0)]
	public MfshCmdContext mfshCmd() {
		MfshCmdContext _localctx = new MfshCmdContext(Context, State);
		EnterRule(_localctx, 18, RULE_mfshCmd);
		try {
			State = 76;
			ErrorHandler.Sync(this);
			switch (TokenStream.LA(1)) {
			case APPLY:
				EnterOuterAlt(_localctx, 1);
				{
				State = 72; apply();
				}
				break;
			case END:
				EnterOuterAlt(_localctx, 2);
				{
				State = 73; end();
				}
				break;
			case INCOMPATIBLE:
				EnterOuterAlt(_localctx, 3);
				{
				State = 74; incompatible();
				}
				break;
			case MACRO:
				EnterOuterAlt(_localctx, 4);
				{
				State = 75; macro();
				}
				break;
			default:
				throw new NoViableAltException(this);
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class ApplyContext : ParserRuleContext {
		public ITerminalNode APPLY() { return GetToken(MFSHParser.APPLY, 0); }
		public ITerminalNode NAME() { return GetToken(MFSHParser.NAME, 0); }
		public ITerminalNode OPAR() { return GetToken(MFSHParser.OPAR, 0); }
		public ITerminalNode CPAR() { return GetToken(MFSHParser.CPAR, 0); }
		public AnyStringContext[] anyString() {
			return GetRuleContexts<AnyStringContext>();
		}
		public AnyStringContext anyString(int i) {
			return GetRuleContext<AnyStringContext>(i);
		}
		public ITerminalNode[] COMMA() { return GetTokens(MFSHParser.COMMA); }
		public ITerminalNode COMMA(int i) {
			return GetToken(MFSHParser.COMMA, i);
		}
		public ApplyContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_apply; } }
		public override TResult Accept<TResult>(IParseTreeVisitor<TResult> visitor) {
			IMFSHParserVisitor<TResult> typedVisitor = visitor as IMFSHParserVisitor<TResult>;
			if (typedVisitor != null) return typedVisitor.VisitApply(this);
			else return visitor.VisitChildren(this);
		}
	}

	[RuleVersion(0)]
	public ApplyContext apply() {
		ApplyContext _localctx = new ApplyContext(Context, State);
		EnterRule(_localctx, 20, RULE_apply);
		int _la;
		try {
			EnterOuterAlt(_localctx, 1);
			{
			State = 78; Match(APPLY);
			State = 79; Match(NAME);
			State = 80; Match(OPAR);
			State = 89;
			ErrorHandler.Sync(this);
			_la = TokenStream.LA(1);
			if (_la==STRING || _la==MULTILINE_STRING) {
				{
				State = 81; anyString();
				State = 86;
				ErrorHandler.Sync(this);
				_la = TokenStream.LA(1);
				while (_la==COMMA) {
					{
					{
					State = 82; Match(COMMA);
					State = 83; anyString();
					}
					}
					State = 88;
					ErrorHandler.Sync(this);
					_la = TokenStream.LA(1);
				}
				}
			}

			State = 91; Match(CPAR);
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class EndContext : ParserRuleContext {
		public ITerminalNode END() { return GetToken(MFSHParser.END, 0); }
		public EndContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_end; } }
		public override TResult Accept<TResult>(IParseTreeVisitor<TResult> visitor) {
			IMFSHParserVisitor<TResult> typedVisitor = visitor as IMFSHParserVisitor<TResult>;
			if (typedVisitor != null) return typedVisitor.VisitEnd(this);
			else return visitor.VisitChildren(this);
		}
	}

	[RuleVersion(0)]
	public EndContext end() {
		EndContext _localctx = new EndContext(Context, State);
		EnterRule(_localctx, 22, RULE_end);
		try {
			EnterOuterAlt(_localctx, 1);
			{
			State = 93; Match(END);
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class IncompatibleContext : ParserRuleContext {
		public ITerminalNode INCOMPATIBLE() { return GetToken(MFSHParser.INCOMPATIBLE, 0); }
		public ITerminalNode NAME() { return GetToken(MFSHParser.NAME, 0); }
		public IncompatibleContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_incompatible; } }
		public override TResult Accept<TResult>(IParseTreeVisitor<TResult> visitor) {
			IMFSHParserVisitor<TResult> typedVisitor = visitor as IMFSHParserVisitor<TResult>;
			if (typedVisitor != null) return typedVisitor.VisitIncompatible(this);
			else return visitor.VisitChildren(this);
		}
	}

	[RuleVersion(0)]
	public IncompatibleContext incompatible() {
		IncompatibleContext _localctx = new IncompatibleContext(Context, State);
		EnterRule(_localctx, 24, RULE_incompatible);
		try {
			EnterOuterAlt(_localctx, 1);
			{
			State = 95; Match(INCOMPATIBLE);
			State = 96; Match(NAME);
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class MacroContext : ParserRuleContext {
		public ITerminalNode MACRO() { return GetToken(MFSHParser.MACRO, 0); }
		public ITerminalNode[] NAME() { return GetTokens(MFSHParser.NAME); }
		public ITerminalNode NAME(int i) {
			return GetToken(MFSHParser.NAME, i);
		}
		public ITerminalNode OPAR() { return GetToken(MFSHParser.OPAR, 0); }
		public ITerminalNode CPAR() { return GetToken(MFSHParser.CPAR, 0); }
		public ITerminalNode ONCE() { return GetToken(MFSHParser.ONCE, 0); }
		public RedirectContext redirect() {
			return GetRuleContext<RedirectContext>(0);
		}
		public ITerminalNode[] COMMA() { return GetTokens(MFSHParser.COMMA); }
		public ITerminalNode COMMA(int i) {
			return GetToken(MFSHParser.COMMA, i);
		}
		public MacroContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_macro; } }
		public override TResult Accept<TResult>(IParseTreeVisitor<TResult> visitor) {
			IMFSHParserVisitor<TResult> typedVisitor = visitor as IMFSHParserVisitor<TResult>;
			if (typedVisitor != null) return typedVisitor.VisitMacro(this);
			else return visitor.VisitChildren(this);
		}
	}

	[RuleVersion(0)]
	public MacroContext macro() {
		MacroContext _localctx = new MacroContext(Context, State);
		EnterRule(_localctx, 26, RULE_macro);
		int _la;
		try {
			EnterOuterAlt(_localctx, 1);
			{
			State = 98; Match(MACRO);
			State = 100;
			ErrorHandler.Sync(this);
			_la = TokenStream.LA(1);
			if (_la==ONCE) {
				{
				State = 99; Match(ONCE);
				}
			}

			State = 102; Match(NAME);
			State = 103; Match(OPAR);
			State = 112;
			ErrorHandler.Sync(this);
			_la = TokenStream.LA(1);
			if (_la==NAME) {
				{
				State = 104; Match(NAME);
				State = 109;
				ErrorHandler.Sync(this);
				_la = TokenStream.LA(1);
				while (_la==COMMA) {
					{
					{
					State = 105; Match(COMMA);
					State = 106; Match(NAME);
					}
					}
					State = 111;
					ErrorHandler.Sync(this);
					_la = TokenStream.LA(1);
				}
				}
			}

			State = 114; Match(CPAR);
			State = 116;
			ErrorHandler.Sync(this);
			_la = TokenStream.LA(1);
			if (_la==GT) {
				{
				State = 115; redirect();
				}
			}

			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class RedirectContext : ParserRuleContext {
		public ITerminalNode GT() { return GetToken(MFSHParser.GT, 0); }
		public SingleStringContext singleString() {
			return GetRuleContext<SingleStringContext>(0);
		}
		public RedirectContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_redirect; } }
		public override TResult Accept<TResult>(IParseTreeVisitor<TResult> visitor) {
			IMFSHParserVisitor<TResult> typedVisitor = visitor as IMFSHParserVisitor<TResult>;
			if (typedVisitor != null) return typedVisitor.VisitRedirect(this);
			else return visitor.VisitChildren(this);
		}
	}

	[RuleVersion(0)]
	public RedirectContext redirect() {
		RedirectContext _localctx = new RedirectContext(Context, State);
		EnterRule(_localctx, 28, RULE_redirect);
		try {
			EnterOuterAlt(_localctx, 1);
			{
			State = 118; Match(GT);
			State = 119; singleString();
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class AnyStringContext : ParserRuleContext {
		public SingleStringContext singleString() {
			return GetRuleContext<SingleStringContext>(0);
		}
		public MultiLineStringContext multiLineString() {
			return GetRuleContext<MultiLineStringContext>(0);
		}
		public AnyStringContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_anyString; } }
		public override TResult Accept<TResult>(IParseTreeVisitor<TResult> visitor) {
			IMFSHParserVisitor<TResult> typedVisitor = visitor as IMFSHParserVisitor<TResult>;
			if (typedVisitor != null) return typedVisitor.VisitAnyString(this);
			else return visitor.VisitChildren(this);
		}
	}

	[RuleVersion(0)]
	public AnyStringContext anyString() {
		AnyStringContext _localctx = new AnyStringContext(Context, State);
		EnterRule(_localctx, 30, RULE_anyString);
		try {
			State = 123;
			ErrorHandler.Sync(this);
			switch (TokenStream.LA(1)) {
			case STRING:
				EnterOuterAlt(_localctx, 1);
				{
				State = 121; singleString();
				}
				break;
			case MULTILINE_STRING:
				EnterOuterAlt(_localctx, 2);
				{
				State = 122; multiLineString();
				}
				break;
			default:
				throw new NoViableAltException(this);
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class MultiLineStringContext : ParserRuleContext {
		public ITerminalNode MULTILINE_STRING() { return GetToken(MFSHParser.MULTILINE_STRING, 0); }
		public MultiLineStringContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_multiLineString; } }
		public override TResult Accept<TResult>(IParseTreeVisitor<TResult> visitor) {
			IMFSHParserVisitor<TResult> typedVisitor = visitor as IMFSHParserVisitor<TResult>;
			if (typedVisitor != null) return typedVisitor.VisitMultiLineString(this);
			else return visitor.VisitChildren(this);
		}
	}

	[RuleVersion(0)]
	public MultiLineStringContext multiLineString() {
		MultiLineStringContext _localctx = new MultiLineStringContext(Context, State);
		EnterRule(_localctx, 32, RULE_multiLineString);
		try {
			EnterOuterAlt(_localctx, 1);
			{
			State = 125; Match(MULTILINE_STRING);
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class SingleStringContext : ParserRuleContext {
		public ITerminalNode STRING() { return GetToken(MFSHParser.STRING, 0); }
		public SingleStringContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_singleString; } }
		public override TResult Accept<TResult>(IParseTreeVisitor<TResult> visitor) {
			IMFSHParserVisitor<TResult> typedVisitor = visitor as IMFSHParserVisitor<TResult>;
			if (typedVisitor != null) return typedVisitor.VisitSingleString(this);
			else return visitor.VisitChildren(this);
		}
	}

	[RuleVersion(0)]
	public SingleStringContext singleString() {
		SingleStringContext _localctx = new SingleStringContext(Context, State);
		EnterRule(_localctx, 34, RULE_singleString);
		try {
			EnterOuterAlt(_localctx, 1);
			{
			State = 127; Match(STRING);
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	private static char[] _serializedATN = {
		'\x3', '\x608B', '\xA72A', '\x8133', '\xB9ED', '\x417C', '\x3BE7', '\x7786', 
		'\x5964', '\x3', '\x19', '\x84', '\x4', '\x2', '\t', '\x2', '\x4', '\x3', 
		'\t', '\x3', '\x4', '\x4', '\t', '\x4', '\x4', '\x5', '\t', '\x5', '\x4', 
		'\x6', '\t', '\x6', '\x4', '\a', '\t', '\a', '\x4', '\b', '\t', '\b', 
		'\x4', '\t', '\t', '\t', '\x4', '\n', '\t', '\n', '\x4', '\v', '\t', '\v', 
		'\x4', '\f', '\t', '\f', '\x4', '\r', '\t', '\r', '\x4', '\xE', '\t', 
		'\xE', '\x4', '\xF', '\t', '\xF', '\x4', '\x10', '\t', '\x10', '\x4', 
		'\x11', '\t', '\x11', '\x4', '\x12', '\t', '\x12', '\x4', '\x13', '\t', 
		'\x13', '\x3', '\x2', '\a', '\x2', '(', '\n', '\x2', '\f', '\x2', '\xE', 
		'\x2', '+', '\v', '\x2', '\x3', '\x2', '\x3', '\x2', '\x3', '\x3', '\x3', 
		'\x3', '\x3', '\x3', '\x3', '\x3', '\x3', '\x3', '\x3', '\x3', '\x3', 
		'\x3', '\x5', '\x3', '\x36', '\n', '\x3', '\x3', '\x4', '\x3', '\x4', 
		'\x3', '\x5', '\x3', '\x5', '\x3', '\x6', '\x3', '\x6', '\x3', '\a', '\x3', 
		'\a', '\x3', '\b', '\x3', '\b', '\x3', '\t', '\x3', '\t', '\x3', '\n', 
		'\x3', '\n', '\a', '\n', '\x46', '\n', '\n', '\f', '\n', '\xE', '\n', 
		'I', '\v', '\n', '\x3', '\v', '\x3', '\v', '\x3', '\v', '\x3', '\v', '\x5', 
		'\v', 'O', '\n', '\v', '\x3', '\f', '\x3', '\f', '\x3', '\f', '\x3', '\f', 
		'\x3', '\f', '\x3', '\f', '\a', '\f', 'W', '\n', '\f', '\f', '\f', '\xE', 
		'\f', 'Z', '\v', '\f', '\x5', '\f', '\\', '\n', '\f', '\x3', '\f', '\x3', 
		'\f', '\x3', '\r', '\x3', '\r', '\x3', '\xE', '\x3', '\xE', '\x3', '\xE', 
		'\x3', '\xF', '\x3', '\xF', '\x5', '\xF', 'g', '\n', '\xF', '\x3', '\xF', 
		'\x3', '\xF', '\x3', '\xF', '\x3', '\xF', '\x3', '\xF', '\a', '\xF', 'n', 
		'\n', '\xF', '\f', '\xF', '\xE', '\xF', 'q', '\v', '\xF', '\x5', '\xF', 
		's', '\n', '\xF', '\x3', '\xF', '\x3', '\xF', '\x5', '\xF', 'w', '\n', 
		'\xF', '\x3', '\x10', '\x3', '\x10', '\x3', '\x10', '\x3', '\x11', '\x3', 
		'\x11', '\x5', '\x11', '~', '\n', '\x11', '\x3', '\x12', '\x3', '\x12', 
		'\x3', '\x13', '\x3', '\x13', '\x3', '\x13', '\x2', '\x2', '\x14', '\x2', 
		'\x4', '\x6', '\b', '\n', '\f', '\xE', '\x10', '\x12', '\x14', '\x16', 
		'\x18', '\x1A', '\x1C', '\x1E', ' ', '\"', '$', '\x2', '\x2', '\x2', '\x83', 
		'\x2', ')', '\x3', '\x2', '\x2', '\x2', '\x4', '\x35', '\x3', '\x2', '\x2', 
		'\x2', '\x6', '\x37', '\x3', '\x2', '\x2', '\x2', '\b', '\x39', '\x3', 
		'\x2', '\x2', '\x2', '\n', ';', '\x3', '\x2', '\x2', '\x2', '\f', '=', 
		'\x3', '\x2', '\x2', '\x2', '\xE', '?', '\x3', '\x2', '\x2', '\x2', '\x10', 
		'\x41', '\x3', '\x2', '\x2', '\x2', '\x12', '\x43', '\x3', '\x2', '\x2', 
		'\x2', '\x14', 'N', '\x3', '\x2', '\x2', '\x2', '\x16', 'P', '\x3', '\x2', 
		'\x2', '\x2', '\x18', '_', '\x3', '\x2', '\x2', '\x2', '\x1A', '\x61', 
		'\x3', '\x2', '\x2', '\x2', '\x1C', '\x64', '\x3', '\x2', '\x2', '\x2', 
		'\x1E', 'x', '\x3', '\x2', '\x2', '\x2', ' ', '}', '\x3', '\x2', '\x2', 
		'\x2', '\"', '\x7F', '\x3', '\x2', '\x2', '\x2', '$', '\x81', '\x3', '\x2', 
		'\x2', '\x2', '&', '(', '\x5', '\x4', '\x3', '\x2', '\'', '&', '\x3', 
		'\x2', '\x2', '\x2', '(', '+', '\x3', '\x2', '\x2', '\x2', ')', '\'', 
		'\x3', '\x2', '\x2', '\x2', ')', '*', '\x3', '\x2', '\x2', '\x2', '*', 
		',', '\x3', '\x2', '\x2', '\x2', '+', ')', '\x3', '\x2', '\x2', '\x2', 
		',', '-', '\a', '\x2', '\x2', '\x3', '-', '\x3', '\x3', '\x2', '\x2', 
		'\x2', '.', '\x36', '\x5', '\x6', '\x4', '\x2', '/', '\x36', '\x5', '\b', 
		'\x5', '\x2', '\x30', '\x36', '\x5', '\n', '\x6', '\x2', '\x31', '\x36', 
		'\x5', '\f', '\a', '\x2', '\x32', '\x36', '\x5', '\xE', '\b', '\x2', '\x33', 
		'\x36', '\x5', '\x10', '\t', '\x2', '\x34', '\x36', '\x5', '\x12', '\n', 
		'\x2', '\x35', '.', '\x3', '\x2', '\x2', '\x2', '\x35', '/', '\x3', '\x2', 
		'\x2', '\x2', '\x35', '\x30', '\x3', '\x2', '\x2', '\x2', '\x35', '\x31', 
		'\x3', '\x2', '\x2', '\x2', '\x35', '\x32', '\x3', '\x2', '\x2', '\x2', 
		'\x35', '\x33', '\x3', '\x2', '\x2', '\x2', '\x35', '\x34', '\x3', '\x2', 
		'\x2', '\x2', '\x36', '\x5', '\x3', '\x2', '\x2', '\x2', '\x37', '\x38', 
		'\a', '\x4', '\x2', '\x2', '\x38', '\a', '\x3', '\x2', '\x2', '\x2', '\x39', 
		':', '\a', '\x5', '\x2', '\x2', ':', '\t', '\x3', '\x2', '\x2', '\x2', 
		';', '<', '\a', '\x6', '\x2', '\x2', '<', '\v', '\x3', '\x2', '\x2', '\x2', 
		'=', '>', '\a', '\a', '\x2', '\x2', '>', '\r', '\x3', '\x2', '\x2', '\x2', 
		'?', '@', '\a', '\b', '\x2', '\x2', '@', '\xF', '\x3', '\x2', '\x2', '\x2', 
		'\x41', '\x42', '\a', '\x17', '\x2', '\x2', '\x42', '\x11', '\x3', '\x2', 
		'\x2', '\x2', '\x43', 'G', '\a', '\x3', '\x2', '\x2', '\x44', '\x46', 
		'\x5', '\x14', '\v', '\x2', '\x45', '\x44', '\x3', '\x2', '\x2', '\x2', 
		'\x46', 'I', '\x3', '\x2', '\x2', '\x2', 'G', '\x45', '\x3', '\x2', '\x2', 
		'\x2', 'G', 'H', '\x3', '\x2', '\x2', '\x2', 'H', '\x13', '\x3', '\x2', 
		'\x2', '\x2', 'I', 'G', '\x3', '\x2', '\x2', '\x2', 'J', 'O', '\x5', '\x16', 
		'\f', '\x2', 'K', 'O', '\x5', '\x18', '\r', '\x2', 'L', 'O', '\x5', '\x1A', 
		'\xE', '\x2', 'M', 'O', '\x5', '\x1C', '\xF', '\x2', 'N', 'J', '\x3', 
		'\x2', '\x2', '\x2', 'N', 'K', '\x3', '\x2', '\x2', '\x2', 'N', 'L', '\x3', 
		'\x2', '\x2', '\x2', 'N', 'M', '\x3', '\x2', '\x2', '\x2', 'O', '\x15', 
		'\x3', '\x2', '\x2', '\x2', 'P', 'Q', '\a', '\n', '\x2', '\x2', 'Q', 'R', 
		'\a', '\x15', '\x2', '\x2', 'R', '[', '\a', '\x11', '\x2', '\x2', 'S', 
		'X', '\x5', ' ', '\x11', '\x2', 'T', 'U', '\a', '\x12', '\x2', '\x2', 
		'U', 'W', '\x5', ' ', '\x11', '\x2', 'V', 'T', '\x3', '\x2', '\x2', '\x2', 
		'W', 'Z', '\x3', '\x2', '\x2', '\x2', 'X', 'V', '\x3', '\x2', '\x2', '\x2', 
		'X', 'Y', '\x3', '\x2', '\x2', '\x2', 'Y', '\\', '\x3', '\x2', '\x2', 
		'\x2', 'Z', 'X', '\x3', '\x2', '\x2', '\x2', '[', 'S', '\x3', '\x2', '\x2', 
		'\x2', '[', '\\', '\x3', '\x2', '\x2', '\x2', '\\', ']', '\x3', '\x2', 
		'\x2', '\x2', ']', '^', '\a', '\x13', '\x2', '\x2', '^', '\x17', '\x3', 
		'\x2', '\x2', '\x2', '_', '`', '\a', '\v', '\x2', '\x2', '`', '\x19', 
		'\x3', '\x2', '\x2', '\x2', '\x61', '\x62', '\a', '\f', '\x2', '\x2', 
		'\x62', '\x63', '\a', '\x15', '\x2', '\x2', '\x63', '\x1B', '\x3', '\x2', 
		'\x2', '\x2', '\x64', '\x66', '\a', '\r', '\x2', '\x2', '\x65', 'g', '\a', 
		'\xE', '\x2', '\x2', '\x66', '\x65', '\x3', '\x2', '\x2', '\x2', '\x66', 
		'g', '\x3', '\x2', '\x2', '\x2', 'g', 'h', '\x3', '\x2', '\x2', '\x2', 
		'h', 'i', '\a', '\x15', '\x2', '\x2', 'i', 'r', '\a', '\x11', '\x2', '\x2', 
		'j', 'o', '\a', '\x15', '\x2', '\x2', 'k', 'l', '\a', '\x12', '\x2', '\x2', 
		'l', 'n', '\a', '\x15', '\x2', '\x2', 'm', 'k', '\x3', '\x2', '\x2', '\x2', 
		'n', 'q', '\x3', '\x2', '\x2', '\x2', 'o', 'm', '\x3', '\x2', '\x2', '\x2', 
		'o', 'p', '\x3', '\x2', '\x2', '\x2', 'p', 's', '\x3', '\x2', '\x2', '\x2', 
		'q', 'o', '\x3', '\x2', '\x2', '\x2', 'r', 'j', '\x3', '\x2', '\x2', '\x2', 
		'r', 's', '\x3', '\x2', '\x2', '\x2', 's', 't', '\x3', '\x2', '\x2', '\x2', 
		't', 'v', '\a', '\x13', '\x2', '\x2', 'u', 'w', '\x5', '\x1E', '\x10', 
		'\x2', 'v', 'u', '\x3', '\x2', '\x2', '\x2', 'v', 'w', '\x3', '\x2', '\x2', 
		'\x2', 'w', '\x1D', '\x3', '\x2', '\x2', '\x2', 'x', 'y', '\a', '\x14', 
		'\x2', '\x2', 'y', 'z', '\x5', '$', '\x13', '\x2', 'z', '\x1F', '\x3', 
		'\x2', '\x2', '\x2', '{', '~', '\x5', '$', '\x13', '\x2', '|', '~', '\x5', 
		'\"', '\x12', '\x2', '}', '{', '\x3', '\x2', '\x2', '\x2', '}', '|', '\x3', 
		'\x2', '\x2', '\x2', '~', '!', '\x3', '\x2', '\x2', '\x2', '\x7F', '\x80', 
		'\a', '\x10', '\x2', '\x2', '\x80', '#', '\x3', '\x2', '\x2', '\x2', '\x81', 
		'\x82', '\a', '\xF', '\x2', '\x2', '\x82', '%', '\x3', '\x2', '\x2', '\x2', 
		'\r', ')', '\x35', 'G', 'N', 'X', '[', '\x66', 'o', 'r', 'v', '}',
	};

	public static readonly ATN _ATN =
		new ATNDeserializer().Deserialize(_serializedATN);


}
} // namespace Eir.MFSH.Parser
