//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     ANTLR Version: 4.8
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from MFSHLexer.g4 by ANTLR 4.8

// Unreachable code detected
#pragma warning disable 0162
// The variable '...' is assigned but its value is never used
#pragma warning disable 0219
// Missing XML comment for publicly visible type or member '...'
#pragma warning disable 1591
// Ambiguous reference in cref attribute
#pragma warning disable 419

namespace MFSH.Parser {
using System;
using System.IO;
using System.Text;
using Antlr4.Runtime;
using Antlr4.Runtime.Atn;
using Antlr4.Runtime.Misc;
using DFA = Antlr4.Runtime.Dfa.DFA;

[System.CodeDom.Compiler.GeneratedCode("ANTLR", "4.8")]
[System.CLSCompliant(false)]
public partial class MFSHLexer : Lexer {
	protected static DFA[] decisionToDFA;
	protected static PredictionContextCache sharedContextCache = new PredictionContextCache();
	public const int
		APPLY=1, END=2, FSHLINE=3, INCLUDE=4, JSONARRAY=5, MACRO=6, PROFILE=7, 
		TEXT=8, USE=9, STRING=10, MULTILINE_STRING=11, OPAR=12, COMMA=13, CPAR=14, 
		GT=15, NAME=16, WS=17;
	public static string[] channelNames = {
		"DEFAULT_TOKEN_CHANNEL", "HIDDEN"
	};

	public static string[] modeNames = {
		"DEFAULT_MODE"
	};

	public static readonly string[] ruleNames = {
		"APPLY", "END", "FSHLINE", "INCLUDE", "JSONARRAY", "MACRO", "PROFILE", 
		"TEXT", "USE", "STRING", "MULTILINE_STRING", "OPAR", "COMMA", "CPAR", 
		"GT", "NAME", "WS"
	};


	public MFSHLexer(ICharStream input)
	: this(input, Console.Out, Console.Error) { }

	public MFSHLexer(ICharStream input, TextWriter output, TextWriter errorOutput)
	: base(input, output, errorOutput)
	{
		Interpreter = new LexerATNSimulator(this, _ATN, decisionToDFA, sharedContextCache);
	}

	private static readonly string[] _LiteralNames = {
		null, "'apply'", "'end'", "'FshLine'", "'include'", "'jsonArray'", "'macro'", 
		"'profile'", "'text'", "'use'", null, null, "'('", "','", "')'", "'>'"
	};
	private static readonly string[] _SymbolicNames = {
		null, "APPLY", "END", "FSHLINE", "INCLUDE", "JSONARRAY", "MACRO", "PROFILE", 
		"TEXT", "USE", "STRING", "MULTILINE_STRING", "OPAR", "COMMA", "CPAR", 
		"GT", "NAME", "WS"
	};
	public static readonly IVocabulary DefaultVocabulary = new Vocabulary(_LiteralNames, _SymbolicNames);

	[NotNull]
	public override IVocabulary Vocabulary
	{
		get
		{
			return DefaultVocabulary;
		}
	}

	public override string GrammarFileName { get { return "MFSHLexer.g4"; } }

	public override string[] RuleNames { get { return ruleNames; } }

	public override string[] ChannelNames { get { return channelNames; } }

	public override string[] ModeNames { get { return modeNames; } }

	public override string SerializedAtn { get { return new string(_serializedATN); } }

	static MFSHLexer() {
		decisionToDFA = new DFA[_ATN.NumberOfDecisions];
		for (int i = 0; i < _ATN.NumberOfDecisions; i++) {
			decisionToDFA[i] = new DFA(_ATN.GetDecisionState(i), i);
		}
	}
	private static char[] _serializedATN = {
		'\x3', '\x608B', '\xA72A', '\x8133', '\xB9ED', '\x417C', '\x3BE7', '\x7786', 
		'\x5964', '\x2', '\x13', '\xA0', '\b', '\x1', '\x4', '\x2', '\t', '\x2', 
		'\x4', '\x3', '\t', '\x3', '\x4', '\x4', '\t', '\x4', '\x4', '\x5', '\t', 
		'\x5', '\x4', '\x6', '\t', '\x6', '\x4', '\a', '\t', '\a', '\x4', '\b', 
		'\t', '\b', '\x4', '\t', '\t', '\t', '\x4', '\n', '\t', '\n', '\x4', '\v', 
		'\t', '\v', '\x4', '\f', '\t', '\f', '\x4', '\r', '\t', '\r', '\x4', '\xE', 
		'\t', '\xE', '\x4', '\xF', '\t', '\xF', '\x4', '\x10', '\t', '\x10', '\x4', 
		'\x11', '\t', '\x11', '\x4', '\x12', '\t', '\x12', '\x3', '\x2', '\x3', 
		'\x2', '\x3', '\x2', '\x3', '\x2', '\x3', '\x2', '\x3', '\x2', '\x3', 
		'\x3', '\x3', '\x3', '\x3', '\x3', '\x3', '\x3', '\x3', '\x4', '\x3', 
		'\x4', '\x3', '\x4', '\x3', '\x4', '\x3', '\x4', '\x3', '\x4', '\x3', 
		'\x4', '\x3', '\x4', '\x3', '\x5', '\x3', '\x5', '\x3', '\x5', '\x3', 
		'\x5', '\x3', '\x5', '\x3', '\x5', '\x3', '\x5', '\x3', '\x5', '\x3', 
		'\x6', '\x3', '\x6', '\x3', '\x6', '\x3', '\x6', '\x3', '\x6', '\x3', 
		'\x6', '\x3', '\x6', '\x3', '\x6', '\x3', '\x6', '\x3', '\x6', '\x3', 
		'\a', '\x3', '\a', '\x3', '\a', '\x3', '\a', '\x3', '\a', '\x3', '\a', 
		'\x3', '\b', '\x3', '\b', '\x3', '\b', '\x3', '\b', '\x3', '\b', '\x3', 
		'\b', '\x3', '\b', '\x3', '\b', '\x3', '\t', '\x3', '\t', '\x3', '\t', 
		'\x3', '\t', '\x3', '\t', '\x3', '\n', '\x3', '\n', '\x3', '\n', '\x3', 
		'\n', '\x3', '\v', '\x3', '\v', '\x3', '\v', '\x3', '\v', '\a', '\v', 
		'\x65', '\n', '\v', '\f', '\v', '\xE', '\v', 'h', '\v', '\v', '\x3', '\v', 
		'\x3', '\v', '\x3', '\f', '\x3', '\f', '\x3', '\f', '\x3', '\f', '\x3', 
		'\f', '\a', '\f', 'q', '\n', '\f', '\f', '\f', '\xE', '\f', 't', '\v', 
		'\f', '\x3', '\f', '\x3', '\f', '\x3', '\f', '\x3', '\f', '\x3', '\r', 
		'\x3', '\r', '\x3', '\xE', '\x3', '\xE', '\x3', '\xF', '\x3', '\xF', '\x3', 
		'\x10', '\x3', '\x10', '\x3', '\x11', '\x3', '\x11', '\x6', '\x11', '\x84', 
		'\n', '\x11', '\r', '\x11', '\xE', '\x11', '\x85', '\x3', '\x11', '\x3', 
		'\x11', '\x3', '\x11', '\x6', '\x11', '\x8B', '\n', '\x11', '\r', '\x11', 
		'\xE', '\x11', '\x8C', '\x3', '\x11', '\x3', '\x11', '\x3', '\x11', '\x3', 
		'\x11', '\x6', '\x11', '\x93', '\n', '\x11', '\r', '\x11', '\xE', '\x11', 
		'\x94', '\x3', '\x11', '\x5', '\x11', '\x98', '\n', '\x11', '\x3', '\x12', 
		'\x6', '\x12', '\x9B', '\n', '\x12', '\r', '\x12', '\xE', '\x12', '\x9C', 
		'\x3', '\x12', '\x3', '\x12', '\x3', 'r', '\x2', '\x13', '\x3', '\x3', 
		'\x5', '\x4', '\a', '\x5', '\t', '\x6', '\v', '\a', '\r', '\b', '\xF', 
		'\t', '\x11', '\n', '\x13', '\v', '\x15', '\f', '\x17', '\r', '\x19', 
		'\xE', '\x1B', '\xF', '\x1D', '\x10', '\x1F', '\x11', '!', '\x12', '#', 
		'\x13', '\x3', '\x2', '\a', '\x6', '\x2', '\f', '\f', '\xF', '\xF', '$', 
		'$', '^', '^', '\x4', '\x2', '$', '$', '^', '^', '\x4', '\x2', '\x43', 
		'\\', '\x63', '|', '\x5', '\x2', '\x32', ';', '\x43', '\\', '\x63', '|', 
		'\x5', '\x2', '\v', '\f', '\xF', '\xF', '\"', '\"', '\x2', '\xA8', '\x2', 
		'\x3', '\x3', '\x2', '\x2', '\x2', '\x2', '\x5', '\x3', '\x2', '\x2', 
		'\x2', '\x2', '\a', '\x3', '\x2', '\x2', '\x2', '\x2', '\t', '\x3', '\x2', 
		'\x2', '\x2', '\x2', '\v', '\x3', '\x2', '\x2', '\x2', '\x2', '\r', '\x3', 
		'\x2', '\x2', '\x2', '\x2', '\xF', '\x3', '\x2', '\x2', '\x2', '\x2', 
		'\x11', '\x3', '\x2', '\x2', '\x2', '\x2', '\x13', '\x3', '\x2', '\x2', 
		'\x2', '\x2', '\x15', '\x3', '\x2', '\x2', '\x2', '\x2', '\x17', '\x3', 
		'\x2', '\x2', '\x2', '\x2', '\x19', '\x3', '\x2', '\x2', '\x2', '\x2', 
		'\x1B', '\x3', '\x2', '\x2', '\x2', '\x2', '\x1D', '\x3', '\x2', '\x2', 
		'\x2', '\x2', '\x1F', '\x3', '\x2', '\x2', '\x2', '\x2', '!', '\x3', '\x2', 
		'\x2', '\x2', '\x2', '#', '\x3', '\x2', '\x2', '\x2', '\x3', '%', '\x3', 
		'\x2', '\x2', '\x2', '\x5', '+', '\x3', '\x2', '\x2', '\x2', '\a', '/', 
		'\x3', '\x2', '\x2', '\x2', '\t', '\x37', '\x3', '\x2', '\x2', '\x2', 
		'\v', '?', '\x3', '\x2', '\x2', '\x2', '\r', 'I', '\x3', '\x2', '\x2', 
		'\x2', '\xF', 'O', '\x3', '\x2', '\x2', '\x2', '\x11', 'W', '\x3', '\x2', 
		'\x2', '\x2', '\x13', '\\', '\x3', '\x2', '\x2', '\x2', '\x15', '`', '\x3', 
		'\x2', '\x2', '\x2', '\x17', 'k', '\x3', '\x2', '\x2', '\x2', '\x19', 
		'y', '\x3', '\x2', '\x2', '\x2', '\x1B', '{', '\x3', '\x2', '\x2', '\x2', 
		'\x1D', '}', '\x3', '\x2', '\x2', '\x2', '\x1F', '\x7F', '\x3', '\x2', 
		'\x2', '\x2', '!', '\x97', '\x3', '\x2', '\x2', '\x2', '#', '\x9A', '\x3', 
		'\x2', '\x2', '\x2', '%', '&', '\a', '\x63', '\x2', '\x2', '&', '\'', 
		'\a', 'r', '\x2', '\x2', '\'', '(', '\a', 'r', '\x2', '\x2', '(', ')', 
		'\a', 'n', '\x2', '\x2', ')', '*', '\a', '{', '\x2', '\x2', '*', '\x4', 
		'\x3', '\x2', '\x2', '\x2', '+', ',', '\a', 'g', '\x2', '\x2', ',', '-', 
		'\a', 'p', '\x2', '\x2', '-', '.', '\a', '\x66', '\x2', '\x2', '.', '\x6', 
		'\x3', '\x2', '\x2', '\x2', '/', '\x30', '\a', 'H', '\x2', '\x2', '\x30', 
		'\x31', '\a', 'u', '\x2', '\x2', '\x31', '\x32', '\a', 'j', '\x2', '\x2', 
		'\x32', '\x33', '\a', 'N', '\x2', '\x2', '\x33', '\x34', '\a', 'k', '\x2', 
		'\x2', '\x34', '\x35', '\a', 'p', '\x2', '\x2', '\x35', '\x36', '\a', 
		'g', '\x2', '\x2', '\x36', '\b', '\x3', '\x2', '\x2', '\x2', '\x37', '\x38', 
		'\a', 'k', '\x2', '\x2', '\x38', '\x39', '\a', 'p', '\x2', '\x2', '\x39', 
		':', '\a', '\x65', '\x2', '\x2', ':', ';', '\a', 'n', '\x2', '\x2', ';', 
		'<', '\a', 'w', '\x2', '\x2', '<', '=', '\a', '\x66', '\x2', '\x2', '=', 
		'>', '\a', 'g', '\x2', '\x2', '>', '\n', '\x3', '\x2', '\x2', '\x2', '?', 
		'@', '\a', 'l', '\x2', '\x2', '@', '\x41', '\a', 'u', '\x2', '\x2', '\x41', 
		'\x42', '\a', 'q', '\x2', '\x2', '\x42', '\x43', '\a', 'p', '\x2', '\x2', 
		'\x43', '\x44', '\a', '\x43', '\x2', '\x2', '\x44', '\x45', '\a', 't', 
		'\x2', '\x2', '\x45', '\x46', '\a', 't', '\x2', '\x2', '\x46', 'G', '\a', 
		'\x63', '\x2', '\x2', 'G', 'H', '\a', '{', '\x2', '\x2', 'H', '\f', '\x3', 
		'\x2', '\x2', '\x2', 'I', 'J', '\a', 'o', '\x2', '\x2', 'J', 'K', '\a', 
		'\x63', '\x2', '\x2', 'K', 'L', '\a', '\x65', '\x2', '\x2', 'L', 'M', 
		'\a', 't', '\x2', '\x2', 'M', 'N', '\a', 'q', '\x2', '\x2', 'N', '\xE', 
		'\x3', '\x2', '\x2', '\x2', 'O', 'P', '\a', 'r', '\x2', '\x2', 'P', 'Q', 
		'\a', 't', '\x2', '\x2', 'Q', 'R', '\a', 'q', '\x2', '\x2', 'R', 'S', 
		'\a', 'h', '\x2', '\x2', 'S', 'T', '\a', 'k', '\x2', '\x2', 'T', 'U', 
		'\a', 'n', '\x2', '\x2', 'U', 'V', '\a', 'g', '\x2', '\x2', 'V', '\x10', 
		'\x3', '\x2', '\x2', '\x2', 'W', 'X', '\a', 'v', '\x2', '\x2', 'X', 'Y', 
		'\a', 'g', '\x2', '\x2', 'Y', 'Z', '\a', 'z', '\x2', '\x2', 'Z', '[', 
		'\a', 'v', '\x2', '\x2', '[', '\x12', '\x3', '\x2', '\x2', '\x2', '\\', 
		']', '\a', 'w', '\x2', '\x2', ']', '^', '\a', 'u', '\x2', '\x2', '^', 
		'_', '\a', 'g', '\x2', '\x2', '_', '\x14', '\x3', '\x2', '\x2', '\x2', 
		'`', '\x66', '\a', '$', '\x2', '\x2', '\x61', '\x65', '\n', '\x2', '\x2', 
		'\x2', '\x62', '\x63', '\a', '^', '\x2', '\x2', '\x63', '\x65', '\t', 
		'\x3', '\x2', '\x2', '\x64', '\x61', '\x3', '\x2', '\x2', '\x2', '\x64', 
		'\x62', '\x3', '\x2', '\x2', '\x2', '\x65', 'h', '\x3', '\x2', '\x2', 
		'\x2', '\x66', '\x64', '\x3', '\x2', '\x2', '\x2', '\x66', 'g', '\x3', 
		'\x2', '\x2', '\x2', 'g', 'i', '\x3', '\x2', '\x2', '\x2', 'h', '\x66', 
		'\x3', '\x2', '\x2', '\x2', 'i', 'j', '\a', '$', '\x2', '\x2', 'j', '\x16', 
		'\x3', '\x2', '\x2', '\x2', 'k', 'l', '\a', '$', '\x2', '\x2', 'l', 'm', 
		'\a', '$', '\x2', '\x2', 'm', 'n', '\a', '$', '\x2', '\x2', 'n', 'r', 
		'\x3', '\x2', '\x2', '\x2', 'o', 'q', '\v', '\x2', '\x2', '\x2', 'p', 
		'o', '\x3', '\x2', '\x2', '\x2', 'q', 't', '\x3', '\x2', '\x2', '\x2', 
		'r', 's', '\x3', '\x2', '\x2', '\x2', 'r', 'p', '\x3', '\x2', '\x2', '\x2', 
		's', 'u', '\x3', '\x2', '\x2', '\x2', 't', 'r', '\x3', '\x2', '\x2', '\x2', 
		'u', 'v', '\a', '$', '\x2', '\x2', 'v', 'w', '\a', '$', '\x2', '\x2', 
		'w', 'x', '\a', '$', '\x2', '\x2', 'x', '\x18', '\x3', '\x2', '\x2', '\x2', 
		'y', 'z', '\a', '*', '\x2', '\x2', 'z', '\x1A', '\x3', '\x2', '\x2', '\x2', 
		'{', '|', '\a', '.', '\x2', '\x2', '|', '\x1C', '\x3', '\x2', '\x2', '\x2', 
		'}', '~', '\a', '+', '\x2', '\x2', '~', '\x1E', '\x3', '\x2', '\x2', '\x2', 
		'\x7F', '\x80', '\a', '@', '\x2', '\x2', '\x80', ' ', '\x3', '\x2', '\x2', 
		'\x2', '\x81', '\x83', '\t', '\x4', '\x2', '\x2', '\x82', '\x84', '\t', 
		'\x5', '\x2', '\x2', '\x83', '\x82', '\x3', '\x2', '\x2', '\x2', '\x84', 
		'\x85', '\x3', '\x2', '\x2', '\x2', '\x85', '\x83', '\x3', '\x2', '\x2', 
		'\x2', '\x85', '\x86', '\x3', '\x2', '\x2', '\x2', '\x86', '\x98', '\x3', 
		'\x2', '\x2', '\x2', '\x87', '\x88', '\a', '&', '\x2', '\x2', '\x88', 
		'\x8A', '\t', '\x4', '\x2', '\x2', '\x89', '\x8B', '\t', '\x5', '\x2', 
		'\x2', '\x8A', '\x89', '\x3', '\x2', '\x2', '\x2', '\x8B', '\x8C', '\x3', 
		'\x2', '\x2', '\x2', '\x8C', '\x8A', '\x3', '\x2', '\x2', '\x2', '\x8C', 
		'\x8D', '\x3', '\x2', '\x2', '\x2', '\x8D', '\x8E', '\x3', '\x2', '\x2', 
		'\x2', '\x8E', '\x98', '\a', '&', '\x2', '\x2', '\x8F', '\x90', '\a', 
		'\'', '\x2', '\x2', '\x90', '\x92', '\t', '\x4', '\x2', '\x2', '\x91', 
		'\x93', '\t', '\x5', '\x2', '\x2', '\x92', '\x91', '\x3', '\x2', '\x2', 
		'\x2', '\x93', '\x94', '\x3', '\x2', '\x2', '\x2', '\x94', '\x92', '\x3', 
		'\x2', '\x2', '\x2', '\x94', '\x95', '\x3', '\x2', '\x2', '\x2', '\x95', 
		'\x96', '\x3', '\x2', '\x2', '\x2', '\x96', '\x98', '\a', '\'', '\x2', 
		'\x2', '\x97', '\x81', '\x3', '\x2', '\x2', '\x2', '\x97', '\x87', '\x3', 
		'\x2', '\x2', '\x2', '\x97', '\x8F', '\x3', '\x2', '\x2', '\x2', '\x98', 
		'\"', '\x3', '\x2', '\x2', '\x2', '\x99', '\x9B', '\t', '\x6', '\x2', 
		'\x2', '\x9A', '\x99', '\x3', '\x2', '\x2', '\x2', '\x9B', '\x9C', '\x3', 
		'\x2', '\x2', '\x2', '\x9C', '\x9A', '\x3', '\x2', '\x2', '\x2', '\x9C', 
		'\x9D', '\x3', '\x2', '\x2', '\x2', '\x9D', '\x9E', '\x3', '\x2', '\x2', 
		'\x2', '\x9E', '\x9F', '\b', '\x12', '\x2', '\x2', '\x9F', '$', '\x3', 
		'\x2', '\x2', '\x2', '\v', '\x2', '\x64', '\x66', 'r', '\x85', '\x8C', 
		'\x94', '\x97', '\x9C', '\x3', '\b', '\x2', '\x2',
	};

	public static readonly ATN _ATN =
		new ATNDeserializer().Deserialize(_serializedATN);


}
} // namespace MFSH.Parser
