//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     ANTLR Version: 4.8
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from MFSHLexer.g4 by ANTLR 4.8

// Unreachable code detected
#pragma warning disable 0162
// The variable '...' is assigned but its value is never used
#pragma warning disable 0219
// Missing XML comment for publicly visible type or member '...'
#pragma warning disable 1591
// Ambiguous reference in cref attribute
#pragma warning disable 419

namespace MFSH {
using System;
using System.IO;
using System.Text;
using Antlr4.Runtime;
using Antlr4.Runtime.Atn;
using Antlr4.Runtime.Misc;
using DFA = Antlr4.Runtime.Dfa.DFA;

[System.CodeDom.Compiler.GeneratedCode("ANTLR", "4.8")]
[System.CLSCompliant(false)]
public partial class MFSHLexer : Lexer {
	protected static DFA[] decisionToDFA;
	protected static PredictionContextCache sharedContextCache = new PredictionContextCache();
	public const int
		MSTART=1, LINE=2, BLANKLINE=3, LASTLINE=4, CR=5, Err=6, MINCLUDE=7, MDEFINE=8, 
		MENDDEF=9, MAPPLY=10, MEND=11, MSTRING=12, MOPAR=13, MCOMMA=14, MCPAR=15, 
		MPNAME=16, MWS=17, MCR=18, MErr=19;
	public const int
		MFSH=1;
	public static string[] channelNames = {
		"DEFAULT_TOKEN_CHANNEL", "HIDDEN"
	};

	public static string[] modeNames = {
		"DEFAULT_MODE", "MFSH"
	};

	public static readonly string[] ruleNames = {
		"SPACE", "MSTART", "LINE", "BLANKLINE", "LASTLINE", "CR", "Err", "MINCLUDE", 
		"MDEFINE", "MENDDEF", "MAPPLY", "MEND", "MSTRING", "MOPAR", "MCOMMA", 
		"MCPAR", "MPNAME", "MWS", "MCR", "MErr"
	};


	public MFSHLexer(ICharStream input)
	: this(input, Console.Out, Console.Error) { }

	public MFSHLexer(ICharStream input, TextWriter output, TextWriter errorOutput)
	: base(input, output, errorOutput)
	{
		Interpreter = new LexerATNSimulator(this, _ATN, decisionToDFA, sharedContextCache);
	}

	private static readonly string[] _LiteralNames = {
		null, null, null, null, null, null, null, "'include'", "'define'", "'enddef'", 
		"'apply'", null, null, "'('", "','", "')'"
	};
	private static readonly string[] _SymbolicNames = {
		null, "MSTART", "LINE", "BLANKLINE", "LASTLINE", "CR", "Err", "MINCLUDE", 
		"MDEFINE", "MENDDEF", "MAPPLY", "MEND", "MSTRING", "MOPAR", "MCOMMA", 
		"MCPAR", "MPNAME", "MWS", "MCR", "MErr"
	};
	public static readonly IVocabulary DefaultVocabulary = new Vocabulary(_LiteralNames, _SymbolicNames);

	[NotNull]
	public override IVocabulary Vocabulary
	{
		get
		{
			return DefaultVocabulary;
		}
	}

	public override string GrammarFileName { get { return "MFSHLexer.g4"; } }

	public override string[] RuleNames { get { return ruleNames; } }

	public override string[] ChannelNames { get { return channelNames; } }

	public override string[] ModeNames { get { return modeNames; } }

	public override string SerializedAtn { get { return new string(_serializedATN); } }

	static MFSHLexer() {
		decisionToDFA = new DFA[_ATN.NumberOfDecisions];
		for (int i = 0; i < _ATN.NumberOfDecisions; i++) {
			decisionToDFA[i] = new DFA(_ATN.GetDecisionState(i), i);
		}
	}
	private static char[] _serializedATN = {
		'\x3', '\x608B', '\xA72A', '\x8133', '\xB9ED', '\x417C', '\x3BE7', '\x7786', 
		'\x5964', '\x2', '\x15', '\xB4', '\b', '\x1', '\b', '\x1', '\x4', '\x2', 
		'\t', '\x2', '\x4', '\x3', '\t', '\x3', '\x4', '\x4', '\t', '\x4', '\x4', 
		'\x5', '\t', '\x5', '\x4', '\x6', '\t', '\x6', '\x4', '\a', '\t', '\a', 
		'\x4', '\b', '\t', '\b', '\x4', '\t', '\t', '\t', '\x4', '\n', '\t', '\n', 
		'\x4', '\v', '\t', '\v', '\x4', '\f', '\t', '\f', '\x4', '\r', '\t', '\r', 
		'\x4', '\xE', '\t', '\xE', '\x4', '\xF', '\t', '\xF', '\x4', '\x10', '\t', 
		'\x10', '\x4', '\x11', '\t', '\x11', '\x4', '\x12', '\t', '\x12', '\x4', 
		'\x13', '\t', '\x13', '\x4', '\x14', '\t', '\x14', '\x4', '\x15', '\t', 
		'\x15', '\x3', '\x2', '\x3', '\x2', '\x3', '\x3', '\a', '\x3', '\x30', 
		'\n', '\x3', '\f', '\x3', '\xE', '\x3', '\x33', '\v', '\x3', '\x3', '\x3', 
		'\x3', '\x3', '\x3', '\x3', '\x3', '\x3', '\x3', '\x4', '\a', '\x4', ':', 
		'\n', '\x4', '\f', '\x4', '\xE', '\x4', '=', '\v', '\x4', '\x3', '\x4', 
		'\x3', '\x4', '\a', '\x4', '\x41', '\n', '\x4', '\f', '\x4', '\xE', '\x4', 
		'\x44', '\v', '\x4', '\x3', '\x4', '\x3', '\x4', '\x3', '\x5', '\a', '\x5', 
		'I', '\n', '\x5', '\f', '\x5', '\xE', '\x5', 'L', '\v', '\x5', '\x3', 
		'\x5', '\x3', '\x5', '\x3', '\x6', '\x6', '\x6', 'Q', '\n', '\x6', '\r', 
		'\x6', '\xE', '\x6', 'R', '\x3', '\x6', '\x3', '\x6', '\x3', '\a', '\x3', 
		'\a', '\x3', '\a', '\x3', '\a', '\x3', '\b', '\x3', '\b', '\x3', '\t', 
		'\x3', '\t', '\x3', '\t', '\x3', '\t', '\x3', '\t', '\x3', '\t', '\x3', 
		'\t', '\x3', '\t', '\x3', '\n', '\x3', '\n', '\x3', '\n', '\x3', '\n', 
		'\x3', '\n', '\x3', '\n', '\x3', '\n', '\x3', '\v', '\x3', '\v', '\x3', 
		'\v', '\x3', '\v', '\x3', '\v', '\x3', '\v', '\x3', '\v', '\x3', '\f', 
		'\x3', '\f', '\x3', '\f', '\x3', '\f', '\x3', '\f', '\x3', '\f', '\x3', 
		'\r', '\x3', '\r', '\a', '\r', '{', '\n', '\r', '\f', '\r', '\xE', '\r', 
		'~', '\v', '\r', '\x3', '\r', '\x3', '\r', '\x3', '\r', '\x3', '\r', '\x3', 
		'\xE', '\x3', '\xE', '\a', '\xE', '\x86', '\n', '\xE', '\f', '\xE', '\xE', 
		'\xE', '\x89', '\v', '\xE', '\x3', '\xE', '\x3', '\xE', '\x3', '\xF', 
		'\x3', '\xF', '\x3', '\x10', '\x3', '\x10', '\x3', '\x11', '\x3', '\x11', 
		'\x3', '\x12', '\x3', '\x12', '\x6', '\x12', '\x95', '\n', '\x12', '\r', 
		'\x12', '\xE', '\x12', '\x96', '\x3', '\x12', '\x3', '\x12', '\x3', '\x12', 
		'\x6', '\x12', '\x9C', '\n', '\x12', '\r', '\x12', '\xE', '\x12', '\x9D', 
		'\x3', '\x12', '\x3', '\x12', '\x3', '\x12', '\x3', '\x12', '\x6', '\x12', 
		'\xA4', '\n', '\x12', '\r', '\x12', '\xE', '\x12', '\xA5', '\x3', '\x12', 
		'\x5', '\x12', '\xA9', '\n', '\x12', '\x3', '\x13', '\x3', '\x13', '\x3', 
		'\x13', '\x3', '\x13', '\x3', '\x14', '\x3', '\x14', '\x3', '\x14', '\x3', 
		'\x14', '\x3', '\x15', '\x3', '\x15', '\x2', '\x2', '\x16', '\x4', '\x2', 
		'\x6', '\x3', '\b', '\x4', '\n', '\x5', '\f', '\x6', '\xE', '\a', '\x10', 
		'\b', '\x12', '\t', '\x14', '\n', '\x16', '\v', '\x18', '\f', '\x1A', 
		'\r', '\x1C', '\xE', '\x1E', '\xF', ' ', '\x10', '\"', '\x11', '$', '\x12', 
		'&', '\x13', '(', '\x14', '*', '\x15', '\x4', '\x2', '\x3', '\n', '\x4', 
		'\x2', '\v', '\v', '\"', '\"', '\x4', '\x2', '\f', '\f', '%', '%', '\x3', 
		'\x2', '\f', '\f', '\x3', '\x2', '%', '%', '\x3', '\x2', '$', '$', '\x4', 
		'\x2', '\x43', '\\', '\x63', '|', '\x5', '\x2', '\x32', ';', '\x43', '\\', 
		'\x63', '|', '\x5', '\x2', '\v', '\f', '\"', '\"', '%', '%', '\x2', '\xBD', 
		'\x2', '\x6', '\x3', '\x2', '\x2', '\x2', '\x2', '\b', '\x3', '\x2', '\x2', 
		'\x2', '\x2', '\n', '\x3', '\x2', '\x2', '\x2', '\x2', '\f', '\x3', '\x2', 
		'\x2', '\x2', '\x2', '\xE', '\x3', '\x2', '\x2', '\x2', '\x2', '\x10', 
		'\x3', '\x2', '\x2', '\x2', '\x3', '\x12', '\x3', '\x2', '\x2', '\x2', 
		'\x3', '\x14', '\x3', '\x2', '\x2', '\x2', '\x3', '\x16', '\x3', '\x2', 
		'\x2', '\x2', '\x3', '\x18', '\x3', '\x2', '\x2', '\x2', '\x3', '\x1A', 
		'\x3', '\x2', '\x2', '\x2', '\x3', '\x1C', '\x3', '\x2', '\x2', '\x2', 
		'\x3', '\x1E', '\x3', '\x2', '\x2', '\x2', '\x3', ' ', '\x3', '\x2', '\x2', 
		'\x2', '\x3', '\"', '\x3', '\x2', '\x2', '\x2', '\x3', '$', '\x3', '\x2', 
		'\x2', '\x2', '\x3', '&', '\x3', '\x2', '\x2', '\x2', '\x3', '(', '\x3', 
		'\x2', '\x2', '\x2', '\x3', '*', '\x3', '\x2', '\x2', '\x2', '\x4', ',', 
		'\x3', '\x2', '\x2', '\x2', '\x6', '\x31', '\x3', '\x2', '\x2', '\x2', 
		'\b', ';', '\x3', '\x2', '\x2', '\x2', '\n', 'J', '\x3', '\x2', '\x2', 
		'\x2', '\f', 'P', '\x3', '\x2', '\x2', '\x2', '\xE', 'V', '\x3', '\x2', 
		'\x2', '\x2', '\x10', 'Z', '\x3', '\x2', '\x2', '\x2', '\x12', '\\', '\x3', 
		'\x2', '\x2', '\x2', '\x14', '\x64', '\x3', '\x2', '\x2', '\x2', '\x16', 
		'k', '\x3', '\x2', '\x2', '\x2', '\x18', 'r', '\x3', '\x2', '\x2', '\x2', 
		'\x1A', 'x', '\x3', '\x2', '\x2', '\x2', '\x1C', '\x83', '\x3', '\x2', 
		'\x2', '\x2', '\x1E', '\x8C', '\x3', '\x2', '\x2', '\x2', ' ', '\x8E', 
		'\x3', '\x2', '\x2', '\x2', '\"', '\x90', '\x3', '\x2', '\x2', '\x2', 
		'$', '\xA8', '\x3', '\x2', '\x2', '\x2', '&', '\xAA', '\x3', '\x2', '\x2', 
		'\x2', '(', '\xAE', '\x3', '\x2', '\x2', '\x2', '*', '\xB2', '\x3', '\x2', 
		'\x2', '\x2', ',', '-', '\t', '\x2', '\x2', '\x2', '-', '\x5', '\x3', 
		'\x2', '\x2', '\x2', '.', '\x30', '\x5', '\x4', '\x2', '\x2', '/', '.', 
		'\x3', '\x2', '\x2', '\x2', '\x30', '\x33', '\x3', '\x2', '\x2', '\x2', 
		'\x31', '/', '\x3', '\x2', '\x2', '\x2', '\x31', '\x32', '\x3', '\x2', 
		'\x2', '\x2', '\x32', '\x34', '\x3', '\x2', '\x2', '\x2', '\x33', '\x31', 
		'\x3', '\x2', '\x2', '\x2', '\x34', '\x35', '\a', '%', '\x2', '\x2', '\x35', 
		'\x36', '\x3', '\x2', '\x2', '\x2', '\x36', '\x37', '\b', '\x3', '\x2', 
		'\x2', '\x37', '\a', '\x3', '\x2', '\x2', '\x2', '\x38', ':', '\x5', '\x4', 
		'\x2', '\x2', '\x39', '\x38', '\x3', '\x2', '\x2', '\x2', ':', '=', '\x3', 
		'\x2', '\x2', '\x2', ';', '\x39', '\x3', '\x2', '\x2', '\x2', ';', '<', 
		'\x3', '\x2', '\x2', '\x2', '<', '>', '\x3', '\x2', '\x2', '\x2', '=', 
		';', '\x3', '\x2', '\x2', '\x2', '>', '\x42', '\n', '\x3', '\x2', '\x2', 
		'?', '\x41', '\n', '\x4', '\x2', '\x2', '@', '?', '\x3', '\x2', '\x2', 
		'\x2', '\x41', '\x44', '\x3', '\x2', '\x2', '\x2', '\x42', '@', '\x3', 
		'\x2', '\x2', '\x2', '\x42', '\x43', '\x3', '\x2', '\x2', '\x2', '\x43', 
		'\x45', '\x3', '\x2', '\x2', '\x2', '\x44', '\x42', '\x3', '\x2', '\x2', 
		'\x2', '\x45', '\x46', '\a', '\f', '\x2', '\x2', '\x46', '\t', '\x3', 
		'\x2', '\x2', '\x2', 'G', 'I', '\x5', '\x4', '\x2', '\x2', 'H', 'G', '\x3', 
		'\x2', '\x2', '\x2', 'I', 'L', '\x3', '\x2', '\x2', '\x2', 'J', 'H', '\x3', 
		'\x2', '\x2', '\x2', 'J', 'K', '\x3', '\x2', '\x2', '\x2', 'K', 'M', '\x3', 
		'\x2', '\x2', '\x2', 'L', 'J', '\x3', '\x2', '\x2', '\x2', 'M', 'N', '\a', 
		'\f', '\x2', '\x2', 'N', '\v', '\x3', '\x2', '\x2', '\x2', 'O', 'Q', '\x5', 
		'\x4', '\x2', '\x2', 'P', 'O', '\x3', '\x2', '\x2', '\x2', 'Q', 'R', '\x3', 
		'\x2', '\x2', '\x2', 'R', 'P', '\x3', '\x2', '\x2', '\x2', 'R', 'S', '\x3', 
		'\x2', '\x2', '\x2', 'S', 'T', '\x3', '\x2', '\x2', '\x2', 'T', 'U', '\b', 
		'\x6', '\x3', '\x2', 'U', '\r', '\x3', '\x2', '\x2', '\x2', 'V', 'W', 
		'\a', '\xF', '\x2', '\x2', 'W', 'X', '\x3', '\x2', '\x2', '\x2', 'X', 
		'Y', '\b', '\a', '\x3', '\x2', 'Y', '\xF', '\x3', '\x2', '\x2', '\x2', 
		'Z', '[', '\v', '\x2', '\x2', '\x2', '[', '\x11', '\x3', '\x2', '\x2', 
		'\x2', '\\', ']', '\a', 'k', '\x2', '\x2', ']', '^', '\a', 'p', '\x2', 
		'\x2', '^', '_', '\a', '\x65', '\x2', '\x2', '_', '`', '\a', 'n', '\x2', 
		'\x2', '`', '\x61', '\a', 'w', '\x2', '\x2', '\x61', '\x62', '\a', '\x66', 
		'\x2', '\x2', '\x62', '\x63', '\a', 'g', '\x2', '\x2', '\x63', '\x13', 
		'\x3', '\x2', '\x2', '\x2', '\x64', '\x65', '\a', '\x66', '\x2', '\x2', 
		'\x65', '\x66', '\a', 'g', '\x2', '\x2', '\x66', 'g', '\a', 'h', '\x2', 
		'\x2', 'g', 'h', '\a', 'k', '\x2', '\x2', 'h', 'i', '\a', 'p', '\x2', 
		'\x2', 'i', 'j', '\a', 'g', '\x2', '\x2', 'j', '\x15', '\x3', '\x2', '\x2', 
		'\x2', 'k', 'l', '\a', 'g', '\x2', '\x2', 'l', 'm', '\a', 'p', '\x2', 
		'\x2', 'm', 'n', '\a', '\x66', '\x2', '\x2', 'n', 'o', '\a', '\x66', '\x2', 
		'\x2', 'o', 'p', '\a', 'g', '\x2', '\x2', 'p', 'q', '\a', 'h', '\x2', 
		'\x2', 'q', '\x17', '\x3', '\x2', '\x2', '\x2', 'r', 's', '\a', '\x63', 
		'\x2', '\x2', 's', 't', '\a', 'r', '\x2', '\x2', 't', 'u', '\a', 'r', 
		'\x2', '\x2', 'u', 'v', '\a', 'n', '\x2', '\x2', 'v', 'w', '\a', '{', 
		'\x2', '\x2', 'w', '\x19', '\x3', '\x2', '\x2', '\x2', 'x', '|', '\a', 
		'\f', '\x2', '\x2', 'y', '{', '\x5', '\x4', '\x2', '\x2', 'z', 'y', '\x3', 
		'\x2', '\x2', '\x2', '{', '~', '\x3', '\x2', '\x2', '\x2', '|', 'z', '\x3', 
		'\x2', '\x2', '\x2', '|', '}', '\x3', '\x2', '\x2', '\x2', '}', '\x7F', 
		'\x3', '\x2', '\x2', '\x2', '~', '|', '\x3', '\x2', '\x2', '\x2', '\x7F', 
		'\x80', '\n', '\x5', '\x2', '\x2', '\x80', '\x81', '\x3', '\x2', '\x2', 
		'\x2', '\x81', '\x82', '\b', '\r', '\x4', '\x2', '\x82', '\x1B', '\x3', 
		'\x2', '\x2', '\x2', '\x83', '\x87', '\a', '$', '\x2', '\x2', '\x84', 
		'\x86', '\n', '\x6', '\x2', '\x2', '\x85', '\x84', '\x3', '\x2', '\x2', 
		'\x2', '\x86', '\x89', '\x3', '\x2', '\x2', '\x2', '\x87', '\x85', '\x3', 
		'\x2', '\x2', '\x2', '\x87', '\x88', '\x3', '\x2', '\x2', '\x2', '\x88', 
		'\x8A', '\x3', '\x2', '\x2', '\x2', '\x89', '\x87', '\x3', '\x2', '\x2', 
		'\x2', '\x8A', '\x8B', '\a', '$', '\x2', '\x2', '\x8B', '\x1D', '\x3', 
		'\x2', '\x2', '\x2', '\x8C', '\x8D', '\a', '*', '\x2', '\x2', '\x8D', 
		'\x1F', '\x3', '\x2', '\x2', '\x2', '\x8E', '\x8F', '\a', '.', '\x2', 
		'\x2', '\x8F', '!', '\x3', '\x2', '\x2', '\x2', '\x90', '\x91', '\a', 
		'+', '\x2', '\x2', '\x91', '#', '\x3', '\x2', '\x2', '\x2', '\x92', '\x94', 
		'\t', '\a', '\x2', '\x2', '\x93', '\x95', '\t', '\b', '\x2', '\x2', '\x94', 
		'\x93', '\x3', '\x2', '\x2', '\x2', '\x95', '\x96', '\x3', '\x2', '\x2', 
		'\x2', '\x96', '\x94', '\x3', '\x2', '\x2', '\x2', '\x96', '\x97', '\x3', 
		'\x2', '\x2', '\x2', '\x97', '\xA9', '\x3', '\x2', '\x2', '\x2', '\x98', 
		'\x99', '\a', '&', '\x2', '\x2', '\x99', '\x9B', '\t', '\a', '\x2', '\x2', 
		'\x9A', '\x9C', '\t', '\b', '\x2', '\x2', '\x9B', '\x9A', '\x3', '\x2', 
		'\x2', '\x2', '\x9C', '\x9D', '\x3', '\x2', '\x2', '\x2', '\x9D', '\x9B', 
		'\x3', '\x2', '\x2', '\x2', '\x9D', '\x9E', '\x3', '\x2', '\x2', '\x2', 
		'\x9E', '\x9F', '\x3', '\x2', '\x2', '\x2', '\x9F', '\xA9', '\a', '&', 
		'\x2', '\x2', '\xA0', '\xA1', '\a', '\'', '\x2', '\x2', '\xA1', '\xA3', 
		'\t', '\a', '\x2', '\x2', '\xA2', '\xA4', '\t', '\b', '\x2', '\x2', '\xA3', 
		'\xA2', '\x3', '\x2', '\x2', '\x2', '\xA4', '\xA5', '\x3', '\x2', '\x2', 
		'\x2', '\xA5', '\xA3', '\x3', '\x2', '\x2', '\x2', '\xA5', '\xA6', '\x3', 
		'\x2', '\x2', '\x2', '\xA6', '\xA7', '\x3', '\x2', '\x2', '\x2', '\xA7', 
		'\xA9', '\a', '\'', '\x2', '\x2', '\xA8', '\x92', '\x3', '\x2', '\x2', 
		'\x2', '\xA8', '\x98', '\x3', '\x2', '\x2', '\x2', '\xA8', '\xA0', '\x3', 
		'\x2', '\x2', '\x2', '\xA9', '%', '\x3', '\x2', '\x2', '\x2', '\xAA', 
		'\xAB', '\t', '\t', '\x2', '\x2', '\xAB', '\xAC', '\x3', '\x2', '\x2', 
		'\x2', '\xAC', '\xAD', '\b', '\x13', '\x3', '\x2', '\xAD', '\'', '\x3', 
		'\x2', '\x2', '\x2', '\xAE', '\xAF', '\a', '\xF', '\x2', '\x2', '\xAF', 
		'\xB0', '\x3', '\x2', '\x2', '\x2', '\xB0', '\xB1', '\b', '\x14', '\x3', 
		'\x2', '\xB1', ')', '\x3', '\x2', '\x2', '\x2', '\xB2', '\xB3', '\v', 
		'\x2', '\x2', '\x2', '\xB3', '+', '\x3', '\x2', '\x2', '\x2', '\xF', '\x2', 
		'\x3', '\x31', ';', '\x42', 'J', 'R', '|', '\x87', '\x96', '\x9D', '\xA5', 
		'\xA8', '\x5', '\a', '\x3', '\x2', '\b', '\x2', '\x2', '\x6', '\x2', '\x2',
	};

	public static readonly ATN _ATN =
		new ATNDeserializer().Deserialize(_serializedATN);


}
} // namespace MFSH
